[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Adamaq01 <adamthibert01@gmail.com>"]
edition = "2018"

[dependencies]
aoc-proc-macros = { path = "proc-macros" }
clap = "3.0.0-beta.2"
dotenv = "0.15"
reqwest = { version = "0.10", features = ["blocking"] }
